# Generated by Django 5.0.7 on 2024-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_track_album_alter_track_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccategory',
            name='cover_image',
            field=models.ImageField(default='', upload_to='album_covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocategory',
            name='cover_image',
            field=models.ImageField(default=' ', upload_to='album_covers/'),
            preserve_default=False,
        ),
    ]
