# Generated by Django 5.0.7 on 2024-09-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_musiccategory_cover_image_videocategory_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Music_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.musiccategory'),
        ),
        migrations.AddField(
            model_name='track',
            name='Music_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.musiccategory'),
        ),
        migrations.AddField(
            model_name='video',
            name='Video_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.videocategory'),
        ),
        migrations.AlterField(
            model_name='musiccategory',
            name='cover_image',
            field=models.ImageField(upload_to='music_category_covers/'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='cover_image',
            field=models.ImageField(upload_to='video_category_covers/'),
        ),
    ]
