# Generated by Django 5.0.7 on 2024-09-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_album_music_category_track_music_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(default=' ', upload_to='album_covers/'),
            preserve_default=False,
        ),
    ]
