# Generated by Django 5.1.2 on 2025-06-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_track_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='theme_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
