# Generated by Django 5.1.2 on 2025-10-21 02:40

from django.conf import settings
from django.db import migrations, models
from django.db import transaction


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_track_liked_by_playlist_useraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                # Merge duplicate playlists for the same user and name (keep lowest id)
                (lambda Playlist: (
                    [
                        (
                            lambda user_id, name: (
                                (lambda duplicates: (
                                    [
                                        (
                                            (lambda keep, *others: (
                                                [
                                                    [keep.tracks.add(*[t for t in other.tracks.all()]) for other in others],
                                                    [other.delete() for other in others]
                                                ]
                                            ))(duplicates[0], *duplicates[1:])
                                        )
                                    ] if len(duplicates) > 1 else []
                                ))(list(Playlist.objects.filter(user_id=user_id, name=name).order_by('id')))
                            )
                        )(
                            group['user_id'], group['name']
                        ) for group in Playlist.objects.values('user_id', 'name').annotate(models.Count('id')).filter(id__count__gt=1)
                    ]
                ))(apps.get_model('store', 'Playlist'))
            ),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_playlist_per_user'),
        ),
    ]
