# Generated by Django 5.1.2 on 2025-10-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_playlist_unique_playlist_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playlist',
            name='unique_playlist_per_user',
        ),
    ]
