# Generated by Django 5.1.2 on 2025-10-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_playlist_unique_playlist_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='albums/'),
        ),
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
        ),
    ]
