# Generated by Django 5.1.2 on 2025-11-22 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_album_fichier_album_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat_paiement', models.CharField(default='non_payé', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('sous_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.album')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='store.commande')),
            ],
        ),
    ]
