# Generated by Django 5.1.2 on 2025-12-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_album_artist_alter_track_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='music_category_covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='track_covers/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='video_category_covers/'),
        ),
    ]
