# Generated by Django 5.1.2 on 2025-12-09 10:25

import store.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_musiccategory_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(storage=store.storage_backends.MediaStorage(), upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=store.storage_backends.MediaStorage(), upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.MediaStorage(), upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='musiccategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.MediaStorage(), upload_to='music_category_covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.MediaStorage(), upload_to='track_covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(storage=store.storage_backends.MediaStorage(), upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=store.storage_backends.MediaStorage(), upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.MediaStorage(), upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.MediaStorage(), upload_to='video_category_covers/'),
        ),
    ]
