# Generated by Django 5.1.2 on 2025-12-20 03:39

import store.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_album_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=store.storage_backends.MediaStorage(), upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(storage=store.storage_backends.MediaStorage(), upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=store.storage_backends.MediaStorage(), upload_to='videos/'),
        ),
    ]
