# Generated by Django 5.1.2 on 2025-12-20 04:47

import store.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_album_fichier_alter_track_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='track_covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='video_thumbnails/'),
        ),
    ]
