# Generated by Django 5.1.2 on 2025-12-21 00:35

import store.models
import store.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_album_cover_image_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='images/albums/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=store.storage_backends.MediaStorage(), upload_to='media/albums/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='images/artists/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='images/tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(storage=store.storage_backends.MediaStorage(), upload_to='media/tracks/', validators=[store.models.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=store.storage_backends.MediaStorage(), upload_to='media/videos/', validators=[store.models.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='images/videos/'),
        ),
    ]
