# Generated by Django 5.1.2 on 2025-12-23 00:36

import django.utils.timezone
import store.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_album_cover_image_alter_album_fichier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/originals/')),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opus_file', models.FileField(blank=True, null=True, upload_to='uploads/converted/audio/')),
                ('aac_file', models.FileField(blank=True, null=True, upload_to='uploads/converted/audio/')),
                ('mp4_file', models.FileField(blank=True, null=True, upload_to='uploads/converted/video/')),
                ('webm_file', models.FileField(blank=True, null=True, upload_to='uploads/converted/video/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/')),
            ],
        ),
        migrations.AlterField(
            model_name='musiccategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='images/music_category_covers/'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=store.storage_backends.PublicMediaStorage(), upload_to='images/video_category_covers/'),
        ),
    ]
