# Generated by Django 5.1.2 on 2025-12-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_mediafile_alter_musiccategory_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='conversion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
