# Generated by Django 5.1.2 on 2026-01-15 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0002_profile_bio_profile_location_profile_website'),
        ('store', '0024_mediafile_conversion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default-cover.jpg', upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_tracks',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='store.track'),
        ),
    ]
