"""
Django settings for music_store project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# REMOVED = 'django-insecure-gu8ed)&texd6%8_fm7d8_zu2a)&9anq)kqb@(#4@_usciz!-gz'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'Utilisateurs',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'django.contrib.sites',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'music_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',  # Required for allauth
            ],
        },
    },
]

WSGI_APPLICATION = 'music_store.wsgi.application'


DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT= os.path.join(BASE_DIR,"store/static")
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field


STATIC_URL = '/static/'

# Ici tu déclares ton dossier source (là où tu mets tes images, css, js en dev)
if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / "store" / "static",
    ]

# Ici Django va collecter les fichiers (via collectstatic) uniquement pour la prod
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media/')
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Stripe settings
STRIPE_PUBLIC_KEY = 'pk_test_51S61oJRK50Gi7XBCdeGa9C3OMOUmeowkm5RrEmUNN0aZRCEQzRCCbobdga5a0shIGHKyYNrHlXiLVWysTy9b6atl005zfq4fbp'
# REMOVED = 'REMOVED_SECRET51S61oJRK50Gi7XBCdeGa9C3OMOUmeowkm5RrEmUNN0aZRCEQzRCCbobdga5a0shIGHKyYNrHlXiLVWysTy9b6atl005zfq4fbp'
REMOVED = os.getenv("REMOVED")
# Allauth settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_VERIFICATION = 'none'  # For simplicity, disable email verification
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True

SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'fr_FR',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    },
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
}



# … autres réglages Django …
ORANGE_API_URL = "https://app.paydunya.com/api/v1/softpay/orange-money-mali"
MOOV_API_URL   = "https://app.paydunya.com/api/v1/softpay/moov-mali"
WAVE_API_URL   = "https://…"  # à renseigner si Wave a un endpoint similaire

# Tes clés / tokens
REMOVED = os.getenv("REMOVED")
REMOVED   = os.getenv("REMOVED")
REMOVED   = os.getenv("REMOVED")


# DEBUG = True  # mode dev pour tester localement
DEBUG = os.getenv("DEBUG", "0") == "1"

from storages.backends.s3boto3 import S3Boto3Storage
try:
    # charge un fichier .env en développement si présent (ne doit PAS être committé)
    from dotenv import load_dotenv
    load_dotenv(str(BASE_DIR / '.env'))
except Exception:
    # python-dotenv n'est pas obligatoire en production (Render utilisera les env vars)
    pass

# class MediaStorage(S3Boto3Storage):
#     location = 'media'
#     file_overwrite = False

# Utiliser django-storages avec S3 (compatible Backblaze)
# ------------------------------
# Backblaze S3 / Django-Storages
# ------------------------------
if DEBUG:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
else:
    DEFAULT_FILE_STORAGE = "store.storage_backends.MediaStorage"

# REMOVED = "00567aee715d1ff0000000003"
# REMOVED = "K005XgXB4Fuq4SNxdZNFlab18MTb8Cw"

# AWS_STORAGE_BUCKET_NAME = "music-store0112"
# AWS_S3_ENDPOINT_URL = "https://s3.us-east-005.backblazeb2.com"
# AWS_S3_REGION_NAME = "us-east-005"

# AWS_S3_FILE_OVERWRITE = False
# AWS_QUERYSTRING_AUTH = True       # URLs privées
# AWS_S3_ADDRESSING_STYLE = "virtual"
# AWS_DEFAULT_ACL = None
REMOVED = os.getenv("REMOVED")

REMOVED = os.getenv("REMOVED")
REMOVED = os.getenv("REMOVED")

AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")

AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = True
AWS_S3_ADDRESSING_STYLE = "virtual"
AWS_DEFAULT_ACL = None
